Name:           ros-melodic-rocon-interactions
Version:        0.3.2
Release:        0%{?dist}
Summary:        ROS rocon_interactions package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/rocon_interactions
Source0:        %{name}-%{version}.tar.gz

Requires:       python-rospkg
Requires:       ros-melodic-genpy
Requires:       ros-melodic-rocon-app-manager-msgs
Requires:       ros-melodic-rocon-bubble-icons
Requires:       ros-melodic-rocon-console
Requires:       ros-melodic-rocon-icons
Requires:       ros-melodic-rocon-interaction-msgs
Requires:       ros-melodic-rocon-python-comms
Requires:       ros-melodic-rocon-python-utils
Requires:       ros-melodic-rocon-std-msgs
Requires:       ros-melodic-rocon-uri
Requires:       ros-melodic-rospy
Requires:       ros-melodic-std-msgs
Requires:       ros-melodic-unique-id
BuildRequires:  python-catkin_pkg
BuildRequires:  ros-melodic-catkin
BuildRequires:  ros-melodic-roslint
BuildRequires:  ros-melodic-rostest
BuildRequires:  ros-melodic-rosunit

%description
Interaction management for human interactive agents in the concert.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Fri Apr 12 2019 Daniel Stonier <d.stonier@gmail.com> - 0.3.2-0
- Autogenerated by Bloom

