Name:           ros-indigo-rocon-tools
Version:        0.1.9
Release:        0%{?dist}
Summary:        ROS rocon_tools package

Group:          Development/Libraries
License:        BSD
URL:            http://www.ros.org/wiki/rocon_tools
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       ros-indigo-rocon-console
Requires:       ros-indigo-rocon-ebnf
Requires:       ros-indigo-rocon-interactions
Requires:       ros-indigo-rocon-launch
Requires:       ros-indigo-rocon-master-info
Requires:       ros-indigo-rocon-python-comms
Requires:       ros-indigo-rocon-python-redis
Requires:       ros-indigo-rocon-python-utils
Requires:       ros-indigo-rocon-python-wifi
Requires:       ros-indigo-rocon-semantic-version
Requires:       ros-indigo-rocon-uri
BuildRequires:  ros-indigo-catkin

%description
Utilities and tools developed for rocon, but usable beyond the boundaries of
rocon.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Mon Aug 25 2014 Daniel Stonier <d.stonier@gmail.com> - 0.1.9-0
- Autogenerated by Bloom

