Name:           ros-kinetic-rocon-tools
Version:        0.3.2
Release:        0%{?dist}
Summary:        ROS rocon_tools package

Group:          Development/Libraries
License:        BSD
URL:            http://www.ros.org/wiki/rocon_tools
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       ros-kinetic-rocon-console
Requires:       ros-kinetic-rocon-ebnf
Requires:       ros-kinetic-rocon-interactions
Requires:       ros-kinetic-rocon-launch
Requires:       ros-kinetic-rocon-master-info
Requires:       ros-kinetic-rocon-python-comms
Requires:       ros-kinetic-rocon-python-redis
Requires:       ros-kinetic-rocon-python-utils
Requires:       ros-kinetic-rocon-python-wifi
Requires:       ros-kinetic-rocon-semantic-version
Requires:       ros-kinetic-rocon-uri
BuildRequires:  ros-kinetic-catkin

%description
Utilities and tools developed for rocon, but usable beyond the boundaries of
rocon.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Wed May 11 2016 Daniel Stonier <d.stonier@gmail.com> - 0.3.2-0
- Autogenerated by Bloom

